api_platform:
    title: Blog Post manager
    description: Manage Blog Post usin Api Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
